### ISSUE TITLE
Missing dependencies for atmos stack lookups

### ISSUE THREAD

**Issue by mtb-xt** [cloudposse/github-action-atmos-affected-stacks#41]
## Describe the Bug
If we're using a lookup in our atmos stacks, they run **terraform output** and **nodejs** under the hood.
Such a stack will fail to work on this action, because terraform was removed.

## Expected Behavior
Expected Action to work.

## Steps to Reproduce
1. Use a lookup in your atmos stack:
   ```
   instance_profile: '{{ (atmos.Component "iam-role/azure-agent" .stack).outputs.role.instance_profile }}'
   ```
3. Wait for workflow 'Atmos Terraform Plan' to run.
4. See error for terraform:
   ```
   template: describe-stacks-all-sections:158:24: executing "describe-stacks-all-sections" at <atmos.Component>: error calling Component: 
   exec: "terraform": executable file not found in $PATH

   Error: Process completed with exit code 1.
   ``` 
5. See error for nodejs:
   ```
   BASE: 2ed8c1c34949c843ce6dc2402478e3006c3aa25d refs/heads/main
   template: describe-stacks-all-sections:80:30: executing "describe-stacks-all-sections" at <atmos.Component>: error calling 
   Component: exit status 127
   /usr/bin/env: 'node': No such file or directory
   Error: Process completed with exit code 127.
   ```

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - Workflow file:
```
name: 👽 Atmos Terraform Plan
run-name: 👽 Atmos Terraform Plan

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  atmos-affected:
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'no-plan') }}
    name: Determine Affected Stacks
    runs-on: ["self-hosted", "terraform"]
    steps:
      - id: affected
        uses: cloudposse/github-action-atmos-affected-stacks@v3
        with:
          atmos-version: ${{ vars.ATMOS_VERSION }}
          atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
    outputs:
      stacks: ${{ steps.affected.outputs.matrix }}
      has-affected-stacks: ${{ steps.affected.outputs.has-affected-stacks }}

  atmos-plan:
    needs: ["atmos-affected"]
    if: ${{ needs.atmos-affected.outputs.has-affected-stacks == 'true' }}
    name: Plan (${{ matrix.name }})
    uses: ./.github/workflows/atmos-terraform-plan-matrix.yaml
    strategy:
      matrix: ${{ fromJson(needs.atmos-affected.outputs.stacks) }}
      max-parallel: 1 # This is important to avoid ddos GHA API
      fail-fast: false # Don't fail fast to avoid locking TF State
    with:
      stacks: ${{ matrix.items }}
      atmos-version: ${{ vars.ATMOS_VERSION }}
      atmos-config-path: ${{ vars.ATMOS_CONFIG_PATH }}
    secrets: inherit
```
 - Version - atmos 1.83.1
